"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Status="NEW"|"IN_PROGRESS"|"WAITING_CLIENT"|"CLOSED"; type Priority="NORMAL"|"HIGH"|"URGENT";
type Note={id:number;authorRole:"GLOBAL_ADMIN"|"WORKER"|"CLIENT";authorName:string;note:string;createdAt:string};
type Ticket={id:number;ticketNumber:string;clientId:number;clientName:string;title:string;description:string;priority:Priority;dueAt:string|null;status:Status;resolutionNotes:string|null;createdAt:string;updatedAt:string;notes:Note[]};
type Client={id:number;name:string};
type FormState={clientId:string;title:string;description:string;priority:Priority;dueAt:string};
type TicketPatch={status?:Status;resolutionNotes?:string};
const labels:Record<Status,string>={NEW:"Në pritje / New",IN_PROGRESS:"Duke u përpunuar",WAITING_CLIENT:"Në pritje të klientit",CLOSED:"Përfunduar / Mbyllur"};
const empty:FormState={clientId:"",title:"",description:"",priority:"NORMAL",dueAt:""};
function fmt(v:string|null){if(!v)return "Pa afat";return new Intl.DateTimeFormat("sq-AL",{dateStyle:"medium",timeStyle:v.includes("T")?"short":undefined}).format(new Date(v));}
function inputDate(v:string|null){if(!v)return "";const d=new Date(v);if(Number.isNaN(d.getTime()))return "";const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16);}

export function TicketManager({portal=false,previewClientId=null}:{portal?:boolean;previewClientId?:number|null}){
 const [tickets,setTickets]=useState<Ticket[]>([]),[clients,setClients]=useState<Client[]>([]),[search,setSearch]=useState("");
 const [activeStatus,setActiveStatus]=useState<Status>("NEW");
 const [open,setOpen]=useState(false),[editing,setEditing]=useState<Ticket|null>(null),[detail,setDetail]=useState<Ticket|null>(null),[form,setForm]=useState<FormState>(empty),[note,setNote]=useState(""),[resolution,setResolution]=useState(""),[statusDraft,setStatusDraft]=useState<Status>("NEW");
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const isPreview=portal&&!!previewClientId;
 async function load(){setLoading(true);setError("");try{const params=new URLSearchParams({search});if(previewClientId)params.set("clientId",String(previewClientId));const r=await fetch(`/api/v1/tickets?${params.toString()}`,{cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.error?.message||"Gabim");setTickets(j.data);if(detail){const updated=j.data.find((t:Ticket)=>t.id===detail.id);if(updated){setDetail(updated);setResolution(updated.resolutionNotes||"");setStatusDraft(updated.status);}}}catch(e){setError(e instanceof Error?e.message:"Gabim");}finally{setLoading(false)}}
 useEffect(()=>{void load()},[previewClientId]); useEffect(()=>{const x=setTimeout(()=>void load(),300);return()=>clearTimeout(x)},[search]);
 useEffect(()=>{if(portal&&!isPreview)return;fetch("/api/v1/clients?view=active",{cache:"no-store"}).then(r=>r.json()).then(j=>{if(j.ok)setClients(j.data.map((c:Client)=>({id:c.id,name:c.name})))})},[portal,isPreview]);
 const stats=useMemo(()=>({all:tickets.length,new:tickets.filter(t=>t.status==="NEW").length,work:tickets.filter(t=>t.status==="IN_PROGRESS").length,waiting:tickets.filter(t=>t.status==="WAITING_CLIENT").length,closed:tickets.filter(t=>t.status==="CLOSED").length,urgent:tickets.filter(t=>t.priority==="URGENT"&&t.status!=="CLOSED").length}),[tickets]);
 function openCreate(){setEditing(null);setForm({...empty,clientId:previewClientId?String(previewClientId):""});setOpen(true);setError("");}
 function openEdit(t:Ticket){setEditing(t);setForm({clientId:String(t.clientId),title:t.title,description:t.description,priority:t.priority,dueAt:inputDate(t.dueAt)});setOpen(true);setError("");}
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{const payload={...form,clientId:portal&&!isPreview?null:(previewClientId||Number(form.clientId)||null),dueAt:form.dueAt||null};const r=await fetch(editing?`/api/v1/tickets/${editing.id}`:"/api/v1/tickets",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing?{...payload,clientId:Number(payload.clientId)}:payload)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.error?.message||(editing?"Ticket-i nuk u përditësua.":"Ticket-i nuk u krijua."));setOpen(false);setEditing(null);setForm(empty);setMessage(editing?"Ticket-i u përditësua me sukses.":"Ticket-i u krijua me sukses.");await load();}catch(e){setError(e instanceof Error?e.message:"Gabim");}finally{setSaving(false)}}
 async function patch(t:Ticket,payload:TicketPatch){setSaving(true);setError("");try{const r=await fetch(`/api/v1/tickets/${t.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.error?.message||"Statusi nuk u ndryshua.");setMessage("Ticket-i u përditësua.");await load();}catch(e){setError(e instanceof Error?e.message:"Gabim");}finally{setSaving(false)}}
 async function addNote(e:FormEvent){e.preventDefault();if(!detail||!note.trim())return;setSaving(true);try{const r=await fetch(`/api/v1/tickets/${detail.id}/notes`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({note})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.error?.message||"Shënimi nuk u ruajt.");setNote("");await load();}catch(e){setError(e instanceof Error?e.message:"Gabim");}finally{setSaving(false)}}
 async function remove(t:Ticket){if(!confirm(`A dëshiron ta fshish ${t.ticketNumber}?`))return;const r=await fetch(`/api/v1/tickets/${t.id}`,{method:"DELETE"});const j=await r.json();if(!r.ok||!j.ok){setError(j?.error?.message||"Nuk u fshi.");return}setDetail(null);await load();}
 function card(t:Ticket){return <article key={t.id} className="ticketRow"><div className="ticketRowMain"><small>{t.ticketNumber} · {t.clientName}</small><button onClick={()=>{setDetail(t);setResolution(t.resolutionNotes||"");setStatusDraft(t.status)}}>{t.title}</button><span>{t.description}</span></div><div className="ticketMeta"><span className={`ticketPriority p-${t.priority.toLowerCase()}`}>{t.priority==="HIGH"?"LARTË":t.priority==="URGENT"?"URGJENT":"NORMAL"}</span><small>{fmt(t.dueAt)}</small><button className="secondaryButton compact" onClick={()=>{setDetail(t);setResolution(t.resolutionNotes||"");setStatusDraft(t.status)}}>Hap</button>{!portal&&<button className="secondaryButton compact" onClick={()=>openEdit(t)}>Edito</button>}{!portal&&t.status==="NEW"&&<button className="primaryButton compact" onClick={()=>void patch(t,{status:"IN_PROGRESS"})}>✓ Prano</button>}{!portal&&<button className="dangerButton compact" onClick={()=>void remove(t)}>Fshi</button>}</div></article>}
 return <>
  {!portal&&<section className="ticketStats"><article><small>Gjithsej</small><strong>{stats.all}</strong></article><article><small>Në pritje / New</small><strong>{stats.new}</strong></article><article><small>Duke u përpunuar</small><strong>{stats.work}</strong></article><article className="urgent"><small>Urgjente</small><strong>{stats.urgent}</strong></article><article><small>Mbyllura</small><strong>{stats.closed}</strong></article></section>}
  {message&&<div className="clientAlert success">{message}</div>}{error&&<div className="clientAlert error">{error}</div>}
  <section className={portal?"portalTicketSection":"ticketSystemCard"}><header className="ticketToolbar"><div><h2>{portal?"Ticket-at e mia":"Ticket System"}</h2><p>{portal?"Krijo kërkesa dhe komuniko me SIRA Solutions.":"Menaxho kërkesat, problemet dhe komunikimin me klientët."}</p></div><button className="primaryButton" onClick={openCreate}>+ Ticket i ri</button></header>
   <label className="ticketSearch">⌕ <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Kërko numër, titull ose klient..."/></label>
   {loading?<div className="dashboardEmpty">Duke ngarkuar...</div>:<div className="ticketTabbedWorkspace"><div className="ticketStatusTabs" role="tablist" aria-label="Statusi i ticket-ave">{(["NEW","IN_PROGRESS","WAITING_CLIENT","CLOSED"] as Status[]).map(s=><button key={s} type="button" role="tab" aria-selected={activeStatus===s} className={`${activeStatus===s?"active":""} tab-${s.toLowerCase()}`} onClick={()=>setActiveStatus(s)}><span>{labels[s]}</span><b>{tickets.filter(t=>t.status===s).length}</b></button>)}</div><section className={`ticketLane ticketSingleLane lane-${activeStatus.toLowerCase()}`}><header><div><h3>{labels[activeStatus]}</h3><small>{activeStatus==="NEW"?"Presin pranimin":activeStatus==="IN_PROGRESS"?"Janë në proces":activeStatus==="WAITING_CLIENT"?"Presin përgjigjen e klientit":"Punë të përfunduara"}</small></div><b>{tickets.filter(t=>t.status===activeStatus).length}</b></header><div>{tickets.filter(t=>t.status===activeStatus).map(card)}{!tickets.some(t=>t.status===activeStatus)&&<div className="ticketLaneEmpty">Nuk ka ticket-a</div>}</div></section></div>}
  </section>
  {open&&<div className="modalBackdrop"><form className="modalCard ticketModal ticketFormModal" onSubmit={submit}><header><div><h2>{editing?"Edito ticket-in":"Ticket i ri"}</h2><p>{editing?"Përditëso të dhënat kryesore të ticket-it.":"Regjistro kërkesën shpejt. Kategorinë dhe trajtimin mund ta caktosh pasi ta pranosh."}</p></div><button type="button" className="modalClose" onClick={()=>{setOpen(false);setEditing(null)}}>×</button></header><div className="ticketFormBody">{(!portal||isPreview)&&<label>Klienti<select required value={form.clientId} disabled={isPreview} onChange={e=>setForm({...form,clientId:e.target.value})}><option value="">Zgjidh klientin</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<label>Titulli<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="p.sh. E-mail-i nuk funksionon"/></label><label>Përshkrimi<textarea required rows={6} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Përshkruaj kërkesën ose problemin..."/></label><div className="ticketFormGrid"><label>Prioriteti<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Priority})}><option value="NORMAL">Normal</option><option value="HIGH">Lartë</option><option value="URGENT">Urgjent</option></select></label><label>Afati<input type="datetime-local" value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})}/></label></div></div><footer><button type="button" className="secondaryButton" onClick={()=>{setOpen(false);setEditing(null)}}>Anulo</button><button className="primaryButton" disabled={saving}>{saving?"Duke ruajtur...":editing?"Ruaj ndryshimet":"Krijo ticket-in"}</button></footer></form></div>}
  {detail&&<div className="modalBackdrop"><div className="modalCard ticketDetailModal"><header><div><small>{detail.ticketNumber}</small><h2>{detail.title}</h2><p>{detail.clientName} · {labels[detail.status]}</p></div><button className="modalClose" onClick={()=>setDetail(null)}>×</button></header><div className="ticketDetailBody"><section className="ticketDescription"><h3>Përshkrimi i problemit / kërkesës</h3><p>{detail.description}</p></section><section className="ticketConversation"><h3>Notes / Komunikimi</h3><div className="ticketNotes">{detail.notes.length?detail.notes.map(n=><article key={n.id} className={n.authorRole==="CLIENT"?"clientNote":"siraNote"}><header><strong>{n.authorName}</strong><small>{n.authorRole==="CLIENT"?"Klient":"SIRA Solutions"} · {fmt(n.createdAt)}</small></header><p>{n.note}</p></article>):<div className="ticketLaneEmpty">Ende nuk ka shënime.</div>}</div><form onSubmit={addNote}><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Shkruaj një note / përgjigje..."/><button className="primaryButton" disabled={saving||!note.trim()}>Dërgo</button></form></section>{detail.resolutionNotes&&<section className="resolutionBox"><h3>Resolution Notes</h3><p>{detail.resolutionNotes}</p></section>}{!portal&&<section className="ticketStatusPanel"><div className="ticketStatusHeader"><div><h3>Statusi i ticket-it</h3><p>Zgjidh fazën aktuale të trajtimit.</p></div><span className={`ticketStatusBadge status-${detail.status.toLowerCase()}`}>{labels[detail.status]}</span></div><div className="ticketStatusControl"><label>Statusi<select value={statusDraft} onChange={e=>setStatusDraft(e.target.value as Status)}><option value="NEW">Në pritje / New</option><option value="IN_PROGRESS">Duke u përpunuar</option><option value="WAITING_CLIENT">Në pritje të klientit</option><option value="CLOSED">Përfunduar / Mbyllur</option></select></label>{statusDraft==="CLOSED"&&<label className="ticketResolutionField">Resolution Notes<input value={resolution} onChange={e=>setResolution(e.target.value)} placeholder="Përshkruaj zgjidhjen para mbylljes..."/></label>}<button className="primaryButton" disabled={saving||statusDraft===detail.status||(statusDraft==="CLOSED"&&!resolution.trim())} onClick={()=>void patch(detail,{status:statusDraft,...(statusDraft==="CLOSED"?{resolutionNotes:resolution}:{})})}>Ruaj statusin</button></div><div className="ticketStatusFooter"><button className="secondaryButton" onClick={()=>{setDetail(null);openEdit(detail)}}>Edito ticket-in</button></div></section>}</div></div></div>}
 </>
}
