"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Cycle = "MONTHLY"|"QUARTERLY"|"YEARLY"|"ONE_TIME";
type Owner = "CLIENT"|"COMPANY";
type Status = "ACTIVE"|"INACTIVE"|"CANCELLED";
interface Contract { id:number; ownerType:Owner; clientId:number|null; clientName:string|null; productId:number|null; productName:string|null; title:string; category:string; provider:string|null; reference:string|null; startDate:string; endDate:string|null; price:number; cycle:Cycle; reminderDays:number; cancellationNoticeDays:number; autoRenew:boolean; status:Status; description:string|null; notes:string|null }
interface Client {id:number;name:string;companyName:string|null}
interface Product {id:number;name:string;active:boolean}
const today=()=>new Date().toISOString().slice(0,10);
const emptyForm={ownerType:"CLIENT" as Owner,clientId:"",productId:"",title:"",category:"Hosting / Domain",provider:"",reference:"",startDate:today(),endDate:"",price:"0",cycle:"YEARLY" as Cycle,reminderDays:"30",cancellationNoticeDays:"30",autoRenew:false,status:"ACTIVE" as Status,description:"",notes:""};
const cycleLabel:Record<Cycle,string>={MONTHLY:"Mujore",QUARTERLY:"Tremujore",YEARLY:"Vjetore",ONE_TIME:"Një herë"};
function euro(v:number){return new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(v)}
function daysUntil(date:string|null){if(!date)return null;const d=new Date(`${date}T12:00:00`);const n=new Date();n.setHours(12,0,0,0);return Math.ceil((d.getTime()-n.getTime())/86400000)}

export function ContractManager(){
 const [contracts,setContracts]=useState<Contract[]>([]),[clients,setClients]=useState<Client[]>([]),[products,setProducts]=useState<Product[]>([]);
 const [form,setForm]=useState(emptyForm),[open,setOpen]=useState(false),[editingId,setEditingId]=useState<number|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const [message,setMessage]=useState(""),[error,setError]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState("ALL");
 async function load(){setLoading(true);setError("");try{const [cr,cl,pr]=await Promise.all([fetch("/api/v1/contracts",{cache:"no-store"}),fetch("/api/v1/clients",{cache:"no-store"}),fetch("/api/v1/products",{cache:"no-store"})]);const [cj,clj,pj]=await Promise.all([cr.json(),cl.json(),pr.json()]);if(!cr.ok||!cj.ok)throw new Error(cj?.error?.message||"Kontratat nuk mund të ngarkohen.");setContracts(cj.data);if(cl.ok&&clj.ok)setClients(clj.data);if(pr.ok&&pj.ok)setProducts(pj.data)}catch(e){setError(e instanceof Error?e.message:"Gabim i panjohur.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const dueSoon=useMemo(()=>contracts.filter(c=>{const d=daysUntil(c.endDate);return c.status==="ACTIVE"&&d!==null&&d>=0&&d<=c.reminderDays}).length,[contracts]);
 const clientCount=contracts.filter(c=>c.ownerType==="CLIENT").length, companyCount=contracts.filter(c=>c.ownerType==="COMPANY").length;
 const filtered=useMemo(()=>contracts.filter(c=>{const txt=`${c.title} ${c.clientName??""} ${c.provider??""} ${c.category}`.toLowerCase();const typeOk=filter==="ALL"||c.ownerType===filter||c.status===filter;return typeOk&&(!search||txt.includes(search.toLowerCase()))}),[contracts,search,filter]);
 function create(){setEditingId(null);setForm({...emptyForm,startDate:today()});setOpen(true)}
 function edit(c:Contract){setEditingId(c.id);setForm({ownerType:c.ownerType,clientId:c.clientId?String(c.clientId):"",productId:c.productId?String(c.productId):"",title:c.title,category:c.category,provider:c.provider??"",reference:c.reference??"",startDate:c.startDate,endDate:c.endDate??"",price:String(c.price),cycle:c.cycle,reminderDays:String(c.reminderDays),cancellationNoticeDays:String(c.cancellationNoticeDays),autoRenew:c.autoRenew,status:c.status,description:c.description??"",notes:c.notes??""});setOpen(true)}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");setMessage("");try{const payload={ownerType:form.ownerType,clientId:form.ownerType==="CLIENT"&&form.clientId?Number(form.clientId):null,productId:form.productId?Number(form.productId):null,title:form.title,category:form.category,provider:form.provider||null,reference:form.reference||null,startDate:form.startDate,endDate:form.endDate||null,price:Number(form.price)||0,cycle:form.cycle,reminderDays:Number(form.reminderDays)||0,cancellationNoticeDays:Number(form.cancellationNoticeDays)||0,autoRenew:form.autoRenew,status:form.status,description:form.description||null,notes:form.notes||null};const r=await fetch(editingId?`/api/v1/contracts/${editingId}`:"/api/v1/contracts",{method:editingId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.error?.message||"Kontrata nuk mund të ruhet.");setOpen(false);setMessage(editingId?"Kontrata u përditësua.":"Kontrata u krijua me sukses.");await load()}catch(err){setError(err instanceof Error?err.message:"Gabim i panjohur.")}finally{setSaving(false)}}
 async function remove(c:Contract){if(!window.confirm(`A dëshiron ta fshish kontratën “${c.title}”?`))return;setSaving(true);setError("");try{const r=await fetch(`/api/v1/contracts/${c.id}`,{method:"DELETE"});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.error?.message||"Kontrata nuk mund të fshihet.");setMessage("Kontrata u fshi.");await load()}catch(e){setError(e instanceof Error?e.message:"Gabim i panjohur.")}finally{setSaving(false)}}
 return <>
  <div className="moduleTitleRow"><div><h2>Kontratat & Abonimet</h2><p>Menaxho kontratat e klientëve dhe shpenzimet periodike të SIRA Solutions.</p></div><button className="primaryButton" onClick={create}>+ Kontratë / abonim i ri</button></div>
  <section className="contractStats"><article><small>Gjithsej</small><strong>{contracts.length}</strong></article><article><small>Për klientët</small><strong>{clientCount}</strong></article><article><small>Për kompaninë</small><strong>{companyCount}</strong></article><article className={dueSoon?"danger":""}><small>Skadojnë së shpejti</small><strong>{dueSoon}</strong></article></section>
  {message&&<div className="clientAlert success">{message}</div>}{error&&<div className="clientAlert error">{error}</div>}
  <section className="contractPanel"><div className="contractToolbar"><label><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Kërko kontratë, klient apo furnitor..."/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">Të gjitha</option><option value="CLIENT">Për klientët</option><option value="COMPANY">Për kompaninë</option><option value="ACTIVE">Aktive</option><option value="INACTIVE">Jo aktive</option></select></div>
   {loading?<div className="taskLoading">Duke ngarkuar kontratat...</div>:<div className="contractTableWrap"><table className="contractTable"><thead><tr><th>KONTRATA / ABONIMI</th><th>PRONARI</th><th>FURNITORI</th><th>AFATI</th><th>ÇMIMI</th><th>VEPRIMET</th></tr></thead><tbody>{filtered.map(c=>{const d=daysUntil(c.endDate),expired=d!==null&&d<0,soon=d!==null&&d>=0&&d<=c.reminderDays;return <tr key={c.id} className={expired?"expired":soon?"soon":""}><td><strong>{c.title}</strong><small>{c.category}{c.reference?` · ${c.reference}`:""}</small></td><td><span className="ownerPill">{c.ownerType==="CLIENT"?(c.clientName||"Klient"):"SIRA Solutions"}</span></td><td>{c.provider||"—"}</td><td>{c.endDate?<><b>{new Intl.DateTimeFormat("sq-AL").format(new Date(`${c.endDate}T12:00:00`))}</b>{expired?<small className="dateDanger">Skaduar para {Math.abs(d!)} ditësh</small>:soon?<small className="dateWarning">Skadon pas {d} ditësh</small>:null}</>:"Pa afat"}</td><td><b>{euro(c.price)}</b><small>{cycleLabel[c.cycle]}</small></td><td><div className="textActions"><button onClick={()=>edit(c)}>Edito</button><button className="danger" disabled={saving} onClick={()=>void remove(c)}>Fshije</button></div></td></tr>})}</tbody></table>{!filtered.length&&<div className="catalogEmpty">Nuk ka kontrata që përputhen me filtrin.</div>}</div>}
  </section>
  {open&&<div className="modalBackdrop" onMouseDown={()=>!saving&&setOpen(false)}><div className="clientModal contractModal" onMouseDown={e=>e.stopPropagation()}><div className="modalHeader"><div><h2>{editingId?"Edito kontratën / abonimin":"Kontratë / abonim i ri"}</h2><p>Afati monitorohet automatikisht dhe paraqitet në Dashboard.</p></div><button type="button" className="modalClose" onClick={()=>setOpen(false)}>×</button></div><form className="contractForm" onSubmit={submit}>
   <label><span>Pronari</span><select value={form.ownerType} onChange={e=>setForm({...form,ownerType:e.target.value as Owner,clientId:e.target.value==="COMPANY"?"":form.clientId})}><option value="CLIENT">Klient</option><option value="COMPANY">SIRA Solutions</option></select></label>
   <label><span>Klienti</span><select disabled={form.ownerType!=="CLIENT"} required={form.ownerType==="CLIENT"} value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})}><option value="">Zgjidh klientin</option>{clients.map(c=><option value={c.id} key={c.id}>{c.companyName||c.name}</option>)}</select></label>
   <label><span>Titulli *</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="p.sh. Hosting rumejsa.at"/></label>
   <label><span>Produkti / shërbimi</span><select value={form.productId} onChange={e=>setForm({...form,productId:e.target.value})}><option value="">Pa produkt</option>{products.filter(p=>p.active).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>
   <label><span>Kategoria</span><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Hosting / Domain</option><option>Software / Licencë</option><option>Mirëmbajtje</option><option>Shërbim</option><option>Tjetër</option></select></label>
   <label><span>Furnitori</span><input value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})} placeholder="p.sh. Hostinger, Adobe"/></label>
   <label><span>Domain / licenca / referenca</span><input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} placeholder="p.sh. siraspace.at"/></label>
   <label><span>Data e fillimit</span><input type="date" required value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label>
   <label><span>Data e skadimit</span><input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label>
   <label><span>Çmimi (€)</span><input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label>
   <label><span>Cikli</span><select value={form.cycle} onChange={e=>setForm({...form,cycle:e.target.value as Cycle})}><option value="YEARLY">Vjetor</option><option value="MONTHLY">Mujor</option><option value="QUARTERLY">Tremujor</option><option value="ONE_TIME">Një herë</option></select></label>
   <label><span>Kujtesë para skadimit (ditë)</span><input type="number" min="0" value={form.reminderDays} onChange={e=>setForm({...form,reminderDays:e.target.value})}/></label>
   <label><span>Afati i anulimit (ditë)</span><input type="number" min="0" value={form.cancellationNoticeDays} onChange={e=>setForm({...form,cancellationNoticeDays:e.target.value})}/></label>
   <label><span>Statusi</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Status})}><option value="ACTIVE">Aktiv</option><option value="INACTIVE">Jo aktiv</option><option value="CANCELLED">Anuluar</option></select></label>
   <label className="checkboxField"><input type="checkbox" checked={form.autoRenew} onChange={e=>setForm({...form,autoRenew:e.target.checked})}/><span>Rinovohet automatikisht</span></label>
   <label className="fieldWide"><span>Përshkrimi</span><textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>
   <label className="fieldWide"><span>Shënime</span><textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>
   <div className="modalActions"><button type="button" className="secondaryButton" onClick={()=>setOpen(false)}>Anulo</button><button className="primaryButton" disabled={saving}>{saving?"Duke ruajtur...":editingId?"Ruaj ndryshimet":"Ruaj kontratën"}</button></div>
  </form></div></div>}
 </>
}
