CREATE TABLE IF NOT EXISTS access_registry_entries (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT UNSIGNED NOT NULL,
  client_id BIGINT UNSIGNED NULL,
  name VARCHAR(190) NOT NULL,
  category ENUM('SERVER','HOSTING','DOMAIN','NETWORK','CLOUD','DATABASE','EMAIL','APPLICATION','SOCIAL','OTHER') NOT NULL,
  access_scope ENUM('PERSONAL','SIRA','CLIENT') NOT NULL DEFAULT 'SIRA',
  provider VARCHAR(160) NULL,
  address VARCHAR(255) NULL,
  service_url VARCHAR(500) NULL,
  username VARCHAR(190) NULL,
  vault_provider ENUM('BITWARDEN','VAULTWARDEN','ONEPASSWORD','KEEPASS','OTHER') NULL,
  vault_url VARCHAR(500) NULL,
  vault_reference VARCHAR(190) NULL,
  two_factor_status ENUM('ENABLED','DISABLED','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  renewal_date DATE NULL,
  notes TEXT NULL,
  status ENUM('ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  INDEX idx_access_registry_org (organization_id, status),
  INDEX idx_access_registry_category (organization_id, category),
  INDEX idx_access_registry_renewal (organization_id, renewal_date),
  INDEX idx_access_registry_client (organization_id, client_id),
  CONSTRAINT fk_access_registry_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_access_registry_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
