"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

interface ProductPackage {
  id: number; name: string; category: string; description: string | null; elements: string[]; includes: string[];
  basePrice: number; vatRate: number; billingCycle: "ONE_TIME" | "MONTHLY" | "YEARLY"; unitLabel: string;
  templateTasks: string[]; active: boolean;
}
const emptyForm = { name:"", category:"", description:"", elements:"", includes:"", basePrice:"", vatRate:"20", billingCycle:"ONE_TIME", unitLabel:"Një herë", templateTasks:"" };
const cycleLabels = { ONE_TIME:"Një herë", MONTHLY:"Mujore", YEARLY:"Vjetore" } as const;
function euro(value:number){return new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(value)}
function lines(value:string){return value.split("\n").map(v=>v.trim()).filter(Boolean)}

export function ProductManager(){
  const [products,setProducts]=useState<ProductPackage[]>([]); const [form,setForm]=useState(emptyForm); const [open,setOpen]=useState(false);
  const [editingId,setEditingId]=useState<number|null>(null); const [deleteTarget,setDeleteTarget]=useState<ProductPackage|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [search,setSearch]=useState(""); const [category,setCategory]=useState("ALL");
  async function load(){setLoading(true);setError("");try{const r=await fetch("/api/v1/products",{cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.error?.message||"Produktet nuk mund të ngarkohen.");setProducts(j.data)}catch(e){setError(e instanceof Error?e.message:"Gabim i panjohur.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  const activeCount=useMemo(()=>products.filter(p=>p.active).length,[products]);
  const recurringCount=useMemo(()=>products.filter(p=>p.billingCycle!=="ONE_TIME"&&p.active).length,[products]);
  const archivedCount=products.length-activeCount;
  const categories=useMemo(()=>Array.from(new Set(products.map(p=>p.category))).sort(),[products]);
  const filtered=useMemo(()=>products.filter(p=>(category==="ALL"||p.category===category)&&(!search||`${p.name} ${p.description??""} ${p.category}`.toLowerCase().includes(search.toLowerCase()))),[products,search,category]);
  function openCreate(){setEditingId(null);setForm(emptyForm);setOpen(true)}
  function openEdit(p:ProductPackage){setEditingId(p.id);setForm({name:p.name,category:p.category,description:p.description??"",elements:p.elements.join("\n"),includes:p.includes.join("\n"),basePrice:String(p.basePrice),vatRate:String(p.vatRate),billingCycle:p.billingCycle,unitLabel:p.unitLabel,templateTasks:p.templateTasks.join("\n")});setOpen(true)}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");setMessage("");try{const payload={name:form.name,category:form.category,description:form.description||null,elements:lines(form.elements),includes:lines(form.includes),basePrice:Number(form.basePrice)||0,vatRate:Number(form.vatRate)||0,billingCycle:form.billingCycle,unitLabel:form.unitLabel,templateTasks:lines(form.templateTasks),active:true};const r=await fetch(editingId?`/api/v1/products/${editingId}`:"/api/v1/products",{method:editingId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.error?.message||"Produkti nuk mund të ruhet.");setOpen(false);setMessage(editingId?"Produkti u përditësua.":"Produkti u krijua me sukses.");await load()}catch(err){setError(err instanceof Error?err.message:"Gabim i panjohur.")}finally{setSaving(false)}}
  async function toggle(p:ProductPackage){setSaving(true);setError("");try{const r=await fetch(`/api/v1/products/${p.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:!p.active})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.error?.message||"Statusi nuk mund të ndryshohet.");await load()}catch(e){setError(e instanceof Error?e.message:"Gabim i panjohur.")}finally{setSaving(false)}}
  async function removeProduct(){if(!deleteTarget)return;setSaving(true);setError("");setMessage("");try{const r=await fetch(`/api/v1/products/${deleteTarget.id}`,{method:"DELETE"});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.error?.message||"Produkti nuk mund të fshihet.");setMessage("Produkti u fshi.");setDeleteTarget(null);await load()}catch(e){setError(e instanceof Error?e.message:"Gabim i panjohur.")}finally{setSaving(false)}}
  return <>
    <div className="moduleTitleRow"><div><h2>Produktet & Shërbimet</h2><p>Katalogu i ofertave të SIRA Solutions.</p></div><button className="primaryButton" onClick={openCreate}>+ Shto produkt/shërbim</button></div>
    <section className="catalogStats"><article><span>▣</span><div><small>Gjithsej</small><strong>{products.length}</strong></div></article><article><span>✓</span><div><small>Aktive</small><strong>{activeCount}</strong></div></article><article><span>◷</span><div><small>Mujore/Vjetore</small><strong>{recurringCount}</strong></div></article><article><span>□</span><div><small>Në arkiv</small><strong>{archivedCount}</strong></div></article></section>
    {message&&<div className="clientAlert success">{message}</div>}{error&&<div className="clientAlert error">{error}</div>}
    <section className="catalogPanel"><div className="catalogToolbar"><label><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Kërko produkt, shërbim ose kategori..."/></label><select value={category} onChange={e=>setCategory(e.target.value)}><option value="ALL">Të gjitha kategoritë</option>{categories.map(c=><option key={c}>{c}</option>)}</select><small>{filtered.length} rezultate</small></div>
      {loading?<div className="taskLoading">Duke ngarkuar produktet...</div>:<div className="catalogTableWrap"><table className="catalogTable"><thead><tr><th>PRODUKTI/SHËRBIMI</th><th>KATEGORIA</th><th>ÇMIMI</th><th>TVSH</th><th>NJËSIA</th><th>STATUSI</th><th>VEPRIMET</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} className={!p.active?"inactive":""}><td><strong>{p.name}</strong><small>{p.description||"Pa përshkrim"}</small></td><td><span className="softPill">{p.category}</span></td><td><b>{euro(p.basePrice)}</b></td><td>{p.vatRate}%</td><td><span className="softPill neutral">{p.unitLabel||cycleLabels[p.billingCycle]}</span></td><td><span className={`statusPill ${p.active?"active":"inactive"}`}>{p.active?"Aktiv":"Arkiv"}</span></td><td><div className="tableActions"><button title="Edito" onClick={()=>openEdit(p)}>✎</button><button title={p.active?"Arkivo":"Aktivizo"} onClick={()=>void toggle(p)} disabled={saving}>{p.active?"▣":"↺"}</button><button className="tableDeleteButton" title="Fshi" onClick={()=>setDeleteTarget(p)} disabled={saving}>⌫</button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="catalogEmpty">Nuk u gjet asnjë produkt.</div>}</div>}
    </section>
    {deleteTarget&&<div className="modalBackdrop" onMouseDown={()=>!saving&&setDeleteTarget(null)}><div className="confirmModal" onMouseDown={e=>e.stopPropagation()}><div className="confirmIcon delete">!</div><h2>Fshi produktin?</h2><p>Produkti <strong>{deleteTarget.name}</strong> do të largohet nga katalogu. Ky veprim nuk e fshin historikun e projekteve ekzistuese.</p><div className="confirmActions"><button className="secondaryButton" disabled={saving} onClick={()=>setDeleteTarget(null)}>Anulo</button><button className="dangerButton" disabled={saving} onClick={()=>void removeProduct()}>{saving?"Duke fshirë...":"Fshi"}</button></div></div></div>}
    {open&&<div className="modalBackdrop" onMouseDown={()=>!saving&&setOpen(false)}><div className="clientModal catalogModal" onMouseDown={e=>e.stopPropagation()}><div className="modalHeader"><div><h2>{editingId?"Edito produktin/shërbimin":"Produkt/Shërbim i ri"}</h2><p>Plotëso të dhënat e ofertës.</p></div><button type="button" className="modalClose" onClick={()=>setOpen(false)}>×</button></div><form className="catalogForm" onSubmit={submit}>
      <label><span>Titulli i produktit/shërbimit *</span><input required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="p.sh. Website Profesional"/></label>
      <label><span>Kategoria *</span><input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="p.sh. Web, IT, Marketing"/></label>
      <label className="fieldWide"><span>Përshkrimi</span><textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Përshkrimi i plotë i produktit ose shërbimit..."/></label>
      <label className="fieldWide"><span>Elementet</span><small>Shkruaj një element në secilin rresht.</small><textarea rows={5} value={form.elements} onChange={e=>setForm({...form,elements:e.target.value})} placeholder={"Domain\nHosting\nSSL Certificate\nBusiness Email"}/></label>
      <label className="fieldWide"><span>Çka përmban</span><small>Shkruaj një pikë në secilin rresht.</small><textarea rows={5} value={form.includes} onChange={e=>setForm({...form,includes:e.target.value})} placeholder={"Konsultim dhe planifikim\nDizajn modern\nFaqja kryesore\nFaqja e kontaktit"}/></label>
      <label><span>Çmimi (€)</span><input type="number" min="0" step="0.01" value={form.basePrice} onChange={e=>setForm({...form,basePrice:e.target.value})}/></label><label><span>TVSH (%)</span><input type="number" min="0" max="100" step="0.01" value={form.vatRate} onChange={e=>setForm({...form,vatRate:e.target.value})}/></label>
      <label><span>Cikli</span><select value={form.billingCycle} onChange={e=>setForm({...form,billingCycle:e.target.value as typeof form.billingCycle})}><option value="ONE_TIME">Një herë</option><option value="MONTHLY">Mujore</option><option value="YEARLY">Vjetore</option></select></label><label><span>Njësia</span><input value={form.unitLabel} onChange={e=>setForm({...form,unitLabel:e.target.value})} placeholder="Një herë / Muaj / Vit"/></label>
      <label className="fieldWide"><span>Detyrat standarde</span><small>Opsionale – përdoren si bazë kur krijohet projekti.</small><textarea rows={4} value={form.templateTasks} onChange={e=>setForm({...form,templateTasks:e.target.value})}/></label>
      <div className="modalActions"><button type="button" className="secondaryButton" onClick={()=>setOpen(false)}>Anulo</button><button className="primaryButton" disabled={saving}>{saving?"Duke ruajtur...":editingId?"Ruaj ndryshimet":"Ruaj produktin"}</button></div>
    </form></div></div>}
  </>
}
