import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getAuthSettings, SESSION_COOKIE, verifySessionToken } from "@/core/auth/session";
import { findTicket, softDeleteTicket, updateTicket } from "@/modules/tickets/ticket.repository";
async function session(){return verifySessionToken((await cookies()).get(SESSION_COOKIE)?.value,getAuthSettings().secret);}
const schema=z.object({clientId:z.number().int().positive().optional(),title:z.string().trim().min(2).max(190).optional(),description:z.string().trim().min(2).max(5000).optional(),status:z.enum(["NEW","IN_PROGRESS","WAITING_CLIENT","CLOSED"]).optional(),priority:z.enum(["NORMAL","HIGH","URGENT"]).optional(),dueAt:z.string().nullable().optional(),resolutionNotes:z.string().trim().max(5000).nullable().optional()});
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const s=await session();if(!s)return NextResponse.json({ok:false},{status:401});const id=Number((await params).id);const ticket=await findTicket(1,id,s.role==="CLIENT"?s.clientId:null);if(!ticket)return NextResponse.json({ok:false,error:{message:"Ticket-i nuk u gjet."}},{status:404});if(s.role==="CLIENT")return NextResponse.json({ok:false,error:{message:"Statusin e ndryshon SIRA Solutions."}},{status:403});const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({ok:false,error:{message:"Të dhënat nuk janë valide."}},{status:400});if(parsed.data.status==="CLOSED"&&!(parsed.data.resolutionNotes??ticket.resolutionNotes)?.trim())return NextResponse.json({ok:false,error:{message:"Resolution Notes janë të detyrueshme para mbylljes."}},{status:409});await updateTicket(1,id,parsed.data);return NextResponse.json({ok:true});}
export async function DELETE(_request:Request,{params}:{params:Promise<{id:string}>}){const s=await session();if(!s)return NextResponse.json({ok:false},{status:401});if(s.role==="CLIENT")return NextResponse.json({ok:false,error:{message:"Nuk ke leje për fshirje."}},{status:403});await softDeleteTicket(1,Number((await params).id));return NextResponse.json({ok:true});}
